In [1]:
"""
NumPy 실습 1: ndarray 생성
============================
이 실습에서는 다양한 방법으로 NumPy 배열을 생성하는 방법을 학습합니다.
"""

import numpy as np

print("=" * 60)
print("NumPy ndarray 생성 실습")
print("=" * 60)

NumPy ndarray 생성 실습


In [2]:
# ============================================================
# 실습 1-1: 리스트로부터 배열 생성
# ============================================================
print("\n[실습 1-1] 리스트로부터 배열 생성")
print("-" * 40)

# TODO: 1차원 배열 생성 (1~5)
arr1d = np.array([1, 2, 3, 4, 5])
print(f"1차원 배열: {arr1d}")
print(f"  - shape: {arr1d.shape}")
print(f"  - ndim: {arr1d.ndim}")
print(f"  - dtype: {arr1d.dtype}")

# TODO: 2차원 배열 생성 (3x3)
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(f"\n2차원 배열:\n{arr2d}")
print(f"  - shape: {arr2d.shape}")
print(f"  - ndim: {arr2d.ndim}")

# TODO: 3차원 배열 생성 (2x2x3)
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(f"\n3차원 배열 shape: {arr3d.shape}")


[실습 1-1] 리스트로부터 배열 생성
----------------------------------------
1차원 배열: [1 2 3 4 5]
  - shape: (5,)
  - ndim: 1
  - dtype: int64

2차원 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
  - shape: (3, 3)
  - ndim: 2

3차원 배열 shape: (2, 2, 3)


In [3]:
# ============================================================
# 실습 1-2: 특수 배열 생성
# ============================================================
print("\n[실습 1-2] 특수 배열 생성")
print("-" * 40)

# TODO: zeros - 0으로 채워진 배열 생성 (3x4)
zeros_arr = np.zeros((3, 4))
print(f"zeros (3x4):\n{zeros_arr}")

# TODO: ones - 1로 채워진 배열 생성 (2x3)
ones_arr = np.ones((2, 3))
print(f"\nones (2x3):\n{ones_arr}")

# TODO: full - 특정 값으로 채워진 배열 생성 (2x2, 값=7)
full_arr = np.full((2, 2), 7)
print(f"\nfull (2x2, value=7):\n{full_arr}")

# TODO: eye - 단위 행렬 생성 (4x4)
eye_arr = np.eye(4)
print(f"\neye (4x4):\n{eye_arr}")

# TODO: diag - 대각 행렬 생성
diag_arr = np.diag([1, 2, 3, 4])
print(f"\ndiag([1,2,3,4]):\n{diag_arr}")


[실습 1-2] 특수 배열 생성
----------------------------------------
zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

full (2x2, value=7):
[[7 7]
 [7 7]]

eye (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

diag([1,2,3,4]):
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [4]:
# ============================================================
# 실습 1-3: 수열 생성
# ============================================================
print("\n[실습 1-3] 수열 생성")
print("-" * 40)

# TODO: arange - 0부터 9까지 정수 배열
arr_arange1 = np.arange(10)
print(f"arange(10): {arr_arange1}")

# TODO: arange - 5부터 15까지 2씩 증가
arr_arange2 = np.arange(5, 15, 2)
print(f"arange(5, 15, 2): {arr_arange2}")

# TODO: linspace - 0부터 1까지 5개로 균등 분할
arr_linspace = np.linspace(0, 1, 5)
print(f"linspace(0, 1, 5): {arr_linspace}")

# TODO: linspace - 0부터 100까지 11개로 균등 분할
arr_linspace2 = np.linspace(0, 100, 11)
print(f"linspace(0, 100, 11): {arr_linspace2}")

# TODO: logspace - 10^0 부터 10^3까지 4개
arr_logspace = np.logspace(0, 3, 4)
print(f"logspace(0, 3, 4): {arr_logspace}")


[실습 1-3] 수열 생성
----------------------------------------
arange(10): [0 1 2 3 4 5 6 7 8 9]
arange(5, 15, 2): [ 5  7  9 11 13]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
linspace(0, 100, 11): [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
logspace(0, 3, 4): [   1.   10.  100. 1000.]


In [5]:
# ============================================================
# 실습 1-4: 난수 배열 생성
# ============================================================
print("\n[실습 1-4] 난수 배열 생성")
print("-" * 40)

# 재현성을 위한 시드 설정
np.random.seed(42)

# TODO: rand - 0~1 균등 분포 난수 (3x3)
rand_uniform = np.random.rand(3, 3)
print(f"균등 분포 난수 (3x3):\n{rand_uniform}")

# TODO: randn - 표준 정규 분포 난수 (3x3)
rand_normal = np.random.randn(3, 3)
print(f"\n정규 분포 난수 (3x3):\n{rand_normal}")

# TODO: randint - 0~10 정수 난수 (3x3)
rand_int = np.random.randint(0, 10, size=(3, 3))
print(f"\n정수 난수 0~10 (3x3):\n{rand_int}")

# TODO: choice - 리스트에서 무작위 선택
choices = np.random.choice(['A', 'B', 'C', 'D'], size=5)
print(f"\n무작위 선택: {choices}")


[실습 1-4] 난수 배열 생성
----------------------------------------
균등 분포 난수 (3x3):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

정규 분포 난수 (3x3):
[[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]

정수 난수 0~10 (3x3):
[[2 6 3]
 [8 2 4]
 [2 6 4]]

무작위 선택: ['A' 'C' 'B' 'D' 'A']


In [6]:
# ============================================================
# 실습 1-5: dtype 지정과 변환
# ============================================================
print("\n[실습 1-5] dtype 지정과 변환")
print("-" * 40)

# TODO: float32로 배열 생성
arr_float32 = np.array([1, 2, 3], dtype=np.float32)
print(f"float32 배열: {arr_float32}, dtype: {arr_float32.dtype}")

# TODO: complex128로 배열 생성
arr_complex = np.array([1, 2, 3], dtype=np.complex128)
print(f"complex128 배열: {arr_complex}, dtype: {arr_complex.dtype}")

# TODO: astype으로 형변환
arr_int = np.array([1.7, 2.3, 3.9])
arr_converted = arr_int.astype(np.int32)
print(f"\n원본 (float): {arr_int}")
print(f"변환 (int32): {arr_converted}")


[실습 1-5] dtype 지정과 변환
----------------------------------------
float32 배열: [1. 2. 3.], dtype: float32
complex128 배열: [1.+0.j 2.+0.j 3.+0.j], dtype: complex128

원본 (float): [1.7 2.3 3.9]
변환 (int32): [1 2 3]


In [7]:
# ============================================================
# 실습 1-6: reshape
# ============================================================
print("\n[실습 1-6] reshape")
print("-" * 40)

# 1차원 배열 생성
arr = np.arange(12)
print(f"원본 배열: {arr}")

# TODO: (3, 4)로 reshape
arr_3x4 = arr.reshape(3, 4)
print(f"\nreshape(3, 4):\n{arr_3x4}")

# TODO: (2, 6)로 reshape
arr_2x6 = arr.reshape(2, 6)
print(f"\nreshape(2, 6):\n{arr_2x6}")

# TODO: (2, 2, 3)로 reshape
arr_2x2x3 = arr.reshape(2, 2, 3)
print(f"\nreshape(2, 2, 3):\n{arr_2x2x3}")

# TODO: -1 사용 (자동 계산)
arr_auto = arr.reshape(4, -1)
print(f"\nreshape(4, -1) -> shape: {arr_auto.shape}")



[실습 1-6] reshape
----------------------------------------
원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(2, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

reshape(2, 2, 3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

reshape(4, -1) -> shape: (4, 3)


In [8]:
# ============================================================
# 도전 과제
# ============================================================
print("\n" + "=" * 60)
print("🎯 도전 과제")
print("=" * 60)

print("""
[과제 1] 1부터 100까지의 숫자 중 3의 배수만 포함하는 배열 생성
힌트: np.arange와 step 활용

[과제 2] 5x5 체크보드 패턴 생성 (0과 1이 번갈아 나타남)
힌트: zeros로 시작, 슬라이싱으로 값 채우기

[과제 3] 평균이 50, 표준편차가 10인 정규분포에서 1000개 샘플 추출 후
         기본 통계량(평균, 표준편차, 최소, 최대) 출력
힌트: np.random.normal 사용
""")


🎯 도전 과제

[과제 1] 1부터 100까지의 숫자 중 3의 배수만 포함하는 배열 생성
힌트: np.arange와 step 활용

[과제 2] 5x5 체크보드 패턴 생성 (0과 1이 번갈아 나타남)
힌트: zeros로 시작, 슬라이싱으로 값 채우기

[과제 3] 평균이 50, 표준편차가 10인 정규분포에서 1000개 샘플 추출 후
         기본 통계량(평균, 표준편차, 최소, 최대) 출력
힌트: np.random.normal 사용



In [16]:
# [과제 1] 1부터 100까지의 숫자 중 3의 배수만 포함하는 배열 생성
# 힌트: np.arange와 step 활용

(np.arange(1, 101, 3) - 1)[1:]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [28]:
# [과제 2] 5x5 체크보드 패턴 생성 (0과 1이 번갈아 나타남)
# 힌트: zeros로 시작, 슬라이싱으로 값 채우기

# 5x5 크기의 0으로 채워진 배열 생성
checkboard = np.zeros((5, 5), dtype=int)
print(f"1. 5x5 크기의 0행렬 생성 \n{checkboard}\n")

# 슬라이싱 활용하기
checkboard[::2, ::2] = 1
print(f"2. 체크보드 패턴 1 \n{checkboard}\n")

checkboard[1::2, 1::2] = 1
print(f"3. 체크보드 패턴 2 \n{checkboard}")

1. 5x5 크기의 0행렬 생성 
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

2. 체크보드 패턴 1 
[[1 0 1 0 1]
 [0 0 0 0 0]
 [1 0 1 0 1]
 [0 0 0 0 0]
 [1 0 1 0 1]]

3. 체크보드 패턴 2 
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [34]:
# 참고

np.random.seed(42)

x = (np.random.rand(100)*10).astype(np.int32)
x.sort()
x[50], x.mean()


(np.int32(4), np.float64(4.2))

In [35]:
temp = np.array([np.random.randint(100) for i in range(100)])
temp.sort()
temp[50], temp.mean()

(np.int64(55), np.float64(51.3))

In [37]:
# [과제 3] 평균이 50, 표준편차가 10인 정규분포에서 1000개 샘플 추출 후
#          기본 통계량(평균, 표준편차, 최소, 최대) 출력
# 힌트: np.random.normal 사용

samples = np.random.normal(loc = 50, scale = 10, size = 1000)
print(f"평균: {samples.mean()}")
print(f"표준편차: {samples.std()}")
print(f"최소값: {samples.min()}")
print(f"최대값: {samples.max()}")

평균: 50.17847744716394
표준편차: 9.759411962647546
최소값: 16.48389483095322
최대값: 76.99714140419509
