In [1]:
"""
NumPy 실습 4: 선형대수 연산
============================
이 실습에서는 NumPy의 선형대수 연산을 학습합니다.
"""

import numpy as np

print("=" * 60)
print("NumPy 선형대수 연산 실습")
print("=" * 60)

NumPy 선형대수 연산 실습


In [2]:
# ============================================================
# 실습 4-1: 벡터 연산
# ============================================================
print("\n[실습 4-1] 벡터 연산")
print("-" * 40)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"벡터 a: {a}")
print(f"벡터 b: {b}")

# TODO: 요소별 연산
print(f"\n요소별 덧셈 (a + b): {a + b}")
print(f"요소별 곱셈 (a * b): {a * b}")

# TODO: 내적 (Dot Product)
dot_product = np.dot(a, b)  # 또는 a @ b
print(f"\n내적 (a · b): {dot_product}")
print(f"내적 계산: 1×4 + 2×5 + 3×6 = {1*4 + 2*5 + 3*6}")

# TODO: 벡터 노름 (크기)
norm_a = np.linalg.norm(a)
print(f"\n벡터 a의 L2 노름: {norm_a:.4f}")
print(f"계산: √(1² + 2² + 3²) = √14 = {np.sqrt(14):.4f}")

# 다양한 노름
print(f"L1 노름 (맨해튼): {np.linalg.norm(a, ord=1)}")
print(f"L∞ 노름 (최대): {np.linalg.norm(a, ord=np.inf)}")

# TODO: 단위 벡터 (정규화)
unit_a = a / np.linalg.norm(a)
print(f"\n단위 벡터: {unit_a}")
print(f"단위 벡터 노름: {np.linalg.norm(unit_a):.4f}")

# TODO: 외적 (Cross Product) - 3D 벡터
cross_product = np.cross(a, b)
print(f"\n외적 (a × b): {cross_product}")


[실습 4-1] 벡터 연산
----------------------------------------
벡터 a: [1 2 3]
벡터 b: [4 5 6]

요소별 덧셈 (a + b): [5 7 9]
요소별 곱셈 (a * b): [ 4 10 18]

내적 (a · b): 32
내적 계산: 1×4 + 2×5 + 3×6 = 32

벡터 a의 L2 노름: 3.7417
계산: √(1² + 2² + 3²) = √14 = 3.7417
L1 노름 (맨해튼): 6.0
L∞ 노름 (최대): 3.0

단위 벡터: [0.26726124 0.53452248 0.80178373]
단위 벡터 노름: 1.0000

외적 (a × b): [-3  6 -3]


In [3]:
# ============================================================
# 실습 4-2: 행렬 기본 연산
# ============================================================
print("\n[실습 4-2] 행렬 기본 연산")
print("-" * 40)

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(f"행렬 A:\n{A}")
print(f"\n행렬 B:\n{B}")

# TODO: 요소별 연산
print(f"\n요소별 덧셈 (A + B):\n{A + B}")
print(f"\n요소별 곱셈 (A * B):\n{A * B}")

# TODO: 행렬 곱셈
C = A @ B  # 또는 np.dot(A, B), np.matmul(A, B)
print(f"\n행렬 곱셈 (A @ B):\n{C}")

# 행렬 곱셈 계산 과정
print("\n[행렬 곱셈 계산 과정]")
print(f"C[0,0] = 1×5 + 2×7 = {1*5 + 2*7}")
print(f"C[0,1] = 1×6 + 2×8 = {1*6 + 2*8}")
print(f"C[1,0] = 3×5 + 4×7 = {3*5 + 4*7}")
print(f"C[1,1] = 3×6 + 4×8 = {3*6 + 4*8}")

# TODO: 전치 (Transpose)
print(f"\n전치 (A.T):\n{A.T}")

# TODO: 대각합 (Trace)
trace_A = np.trace(A)
print(f"\n대각합 (trace): {trace_A}")



[실습 4-2] 행렬 기본 연산
----------------------------------------
행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[5 6]
 [7 8]]

요소별 덧셈 (A + B):
[[ 6  8]
 [10 12]]

요소별 곱셈 (A * B):
[[ 5 12]
 [21 32]]

행렬 곱셈 (A @ B):
[[19 22]
 [43 50]]

[행렬 곱셈 계산 과정]
C[0,0] = 1×5 + 2×7 = 19
C[0,1] = 1×6 + 2×8 = 22
C[1,0] = 3×5 + 4×7 = 43
C[1,1] = 3×6 + 4×8 = 50

전치 (A.T):
[[1 3]
 [2 4]]

대각합 (trace): 5


In [4]:
# ============================================================
# 실습 4-3: 행렬식 (Determinant)
# ============================================================
print("\n[실습 4-3] 행렬식")
print("-" * 40)

A = np.array([[1, 2],
              [3, 4]])

det_A = np.linalg.det(A)
print(f"행렬 A:\n{A}")
print(f"\ndet(A) = {det_A:.4f}")
print(f"계산: 1×4 - 2×3 = {1*4 - 2*3}")

# 3x3 행렬
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

det_B = np.linalg.det(B)
print(f"\n3x3 행렬 B:\n{B}")
print(f"det(B) = {det_B:.4f}")

# 특이 행렬 (det = 0)
singular = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
det_singular = np.linalg.det(singular)
print(f"\n특이 행렬:\n{singular}")
print(f"det = {det_singular:.10f} (거의 0)")


[실습 4-3] 행렬식
----------------------------------------
행렬 A:
[[1 2]
 [3 4]]

det(A) = -2.0000
계산: 1×4 - 2×3 = -2

3x3 행렬 B:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
det(B) = -3.0000

특이 행렬:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
det = -0.0000000000 (거의 0)


In [5]:
# ============================================================
# 실습 4-4: 역행렬 (Inverse)
# ============================================================
print("\n[실습 4-4] 역행렬")
print("-" * 40)

A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A)
print(f"행렬 A:\n{A}")
print(f"\n역행렬 A⁻¹:\n{A_inv}")

# 검증: A × A⁻¹ = I
identity = A @ A_inv
print(f"\nA × A⁻¹ (단위행렬):\n{identity}")
print(f"근사 확인: np.allclose(A @ A_inv, I) = {np.allclose(identity, np.eye(2))}")

# 3x3 역행렬
B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
B_inv = np.linalg.inv(B)
print(f"\n3x3 행렬 B:\n{B}")
print(f"\nB의 역행렬:\n{B_inv}")


[실습 4-4] 역행렬
----------------------------------------
행렬 A:
[[1 2]
 [3 4]]

역행렬 A⁻¹:
[[-2.   1. ]
 [ 1.5 -0.5]]

A × A⁻¹ (단위행렬):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
근사 확인: np.allclose(A @ A_inv, I) = True

3x3 행렬 B:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

B의 역행렬:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [6]:
# ============================================================
# 실습 4-5: 선형 방정식 풀기
# ============================================================
print("\n[실습 4-5] 선형 방정식 풀기")
print("-" * 40)

# 연립방정식:
# 2x + y = 5
# x + 3y = 7

print("연립방정식:")
print("  2x +  y = 5")
print("   x + 3y = 7")

A = np.array([[2, 1],
              [1, 3]])
b = np.array([5, 7])

# 방법 1: np.linalg.solve (추천)
x = np.linalg.solve(A, b)
print(f"\n해 (np.linalg.solve): x = {x[0]:.4f}, y = {x[1]:.4f}")

# 방법 2: 역행렬 사용
x_inv = np.linalg.inv(A) @ b
print(f"해 (역행렬): x = {x_inv[0]:.4f}, y = {x_inv[1]:.4f}")

# 검증
print(f"\n검증: A @ x = {A @ x}")

# 더 큰 시스템
print("\n[더 큰 연립방정식]")
# 3x + y - z = 9
# x + 2y + z = 8
# 2x - y + 2z = 3
A = np.array([[3, 1, -1],
              [1, 2, 1],
              [2, -1, 2]])
b = np.array([9, 8, 3])
x = np.linalg.solve(A, b)
print(f"해: x={x[0]:.2f}, y={x[1]:.2f}, z={x[2]:.2f}")
print(f"검증: {A @ x}")



[실습 4-5] 선형 방정식 풀기
----------------------------------------
연립방정식:
  2x +  y = 5
   x + 3y = 7

해 (np.linalg.solve): x = 1.6000, y = 1.8000
해 (역행렬): x = 1.6000, y = 1.8000

검증: A @ x = [5. 7.]

[더 큰 연립방정식]
해: x=2.30, y=2.60, z=0.50
검증: [9. 8. 3.]


In [7]:
# ============================================================
# 실습 4-6: 고유값과 고유벡터
# ============================================================
print("\n[실습 4-6] 고유값과 고유벡터")
print("-" * 40)

A = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"행렬 A:\n{A}")
print(f"\n고유값: {eigenvalues}")
print(f"\n고유벡터 (열 벡터):\n{eigenvectors}")

# 검증: Av = λv
print("\n[검증: Av = λv]")
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lam = eigenvalues[i]
    Av = A @ v
    lam_v = lam * v
    print(f"λ = {lam:.2f}")
    print(f"  A @ v = {Av}")
    print(f"  λ × v = {lam_v}")

# 대칭 행렬 (실수 고유값)
print("\n[대칭 행렬]")
S = np.array([[2, 1],
              [1, 2]])
eigenvalues_s, eigenvectors_s = np.linalg.eigh(S)  # 대칭 행렬용
print(f"대칭 행렬 S:\n{S}")
print(f"고유값: {eigenvalues_s}")


[실습 4-6] 고유값과 고유벡터
----------------------------------------
행렬 A:
[[4 2]
 [1 3]]

고유값: [5. 2.]

고유벡터 (열 벡터):
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

[검증: Av = λv]
λ = 5.00
  A @ v = [4.47213595 2.23606798]
  λ × v = [4.47213595 2.23606798]
λ = 2.00
  A @ v = [-1.41421356  1.41421356]
  λ × v = [-1.41421356  1.41421356]

[대칭 행렬]
대칭 행렬 S:
[[2 1]
 [1 2]]
고유값: [1. 3.]


In [8]:
# ============================================================
# 실습 4-7: 행렬 분해
# ============================================================
print("\n[실습 4-7] 행렬 분해")
print("-" * 40)

# SVD (특이값 분해)
print("[SVD - 특이값 분해]")
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, S, Vt = np.linalg.svd(A)

print(f"행렬 A (3x2):\n{A}")
print(f"\nU (3x3):\n{U}")
print(f"\n특이값 S: {S}")
print(f"\nVt (2x2):\n{Vt}")

# 복원
S_matrix = np.zeros((3, 2))
np.fill_diagonal(S_matrix, S)
A_reconstructed = U @ S_matrix @ Vt
print(f"\n복원된 A:\n{A_reconstructed}")

# QR 분해
print("\n[QR 분해]")
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

Q, R = np.linalg.qr(A)

print(f"행렬 A:\n{A}")
print(f"\nQ (직교 행렬):\n{Q}")
print(f"\nR (상삼각 행렬):\n{R}")
print(f"\nQ @ R:\n{Q @ R}")

# Q가 직교행렬인지 확인
print(f"\nQ.T @ Q (단위행렬):\n{Q.T @ Q}")


[실습 4-7] 행렬 분해
----------------------------------------
[SVD - 특이값 분해]
행렬 A (3x2):
[[1 2]
 [3 4]
 [5 6]]

U (3x3):
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

특이값 S: [9.52551809 0.51430058]

Vt (2x2):
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

복원된 A:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

[QR 분해]
행렬 A:
[[1 2]
 [3 4]
 [5 6]]

Q (직교 행렬):
[[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]

R (상삼각 행렬):
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]

Q @ R:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

Q.T @ Q (단위행렬):
[[1.0000000e+00 1.0875945e-16]
 [1.0875945e-16 1.0000000e+00]]


In [9]:
# ============================================================
# 실습 4-8: 행렬 랭크와 조건수
# ============================================================
print("\n[실습 4-8] 행렬 랭크와 조건수")
print("-" * 40)

# 행렬 랭크
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
rank_A = np.linalg.matrix_rank(A)
print(f"행렬 A:\n{A}")
print(f"랭크: {rank_A}")

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])
rank_B = np.linalg.matrix_rank(B)
print(f"\n행렬 B:\n{B}")
print(f"랭크: {rank_B}")

# 조건수 (Condition Number)
print("\n[조건수]")
well_conditioned = np.array([[1, 0],
                              [0, 1]])
ill_conditioned = np.array([[1, 1],
                             [1, 1.0001]])

cond_well = np.linalg.cond(well_conditioned)
cond_ill = np.linalg.cond(ill_conditioned)

print(f"잘 조건화된 행렬 조건수: {cond_well:.2f}")
print(f"나쁘게 조건화된 행렬 조건수: {cond_ill:.2f}")
print("(조건수가 크면 수치적으로 불안정)")



[실습 4-8] 행렬 랭크와 조건수
----------------------------------------
행렬 A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
랭크: 2

행렬 B:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
랭크: 3

[조건수]
잘 조건화된 행렬 조건수: 1.00
나쁘게 조건화된 행렬 조건수: 40002.00
(조건수가 크면 수치적으로 불안정)


In [10]:
# ============================================================
# 도전 과제
# ============================================================
print("\n" + "=" * 60)
print("🎯 도전 과제")
print("=" * 60)

print("""
[과제 1] 투영 행렬 구현
        - 벡터 a를 벡터 b 방향으로 투영
        - 공식: proj_b(a) = (a·b / b·b) × b

[과제 2] 2x2 회전 행렬 구현
        - 각도 θ만큼 회전하는 행렬 생성
        - 점 (1, 0)을 45도 회전

[과제 3] 최소제곱법으로 선형 회귀
        - 데이터: x = [1, 2, 3, 4, 5], y = [2.1, 3.9, 6.2, 7.8, 10.1]
        - y = ax + b 형태의 직선 적합
""")



🎯 도전 과제

[과제 1] 투영 행렬 구현
        - 벡터 a를 벡터 b 방향으로 투영
        - 공식: proj_b(a) = (a·b / b·b) × b

[과제 2] 2x2 회전 행렬 구현
        - 각도 θ만큼 회전하는 행렬 생성
        - 점 (1, 0)을 45도 회전

[과제 3] 최소제곱법으로 선형 회귀
        - 데이터: x = [1, 2, 3, 4, 5], y = [2.1, 3.9, 6.2, 7.8, 10.1]
        - y = ax + b 형태의 직선 적합



In [11]:
# [과제 1] 투영 행렬 구현
#         - 벡터 a를 벡터 b 방향으로 투영
#         - 공식: proj_b(a) = (a·b / b·b) × b

print("\n[과제 1 해답] 벡터 투영")
a = np.array([3, 4])
b = np.array([1, 0])

# a를 b 방향으로 투영
proj = (np.dot(a, b) / np.dot(b, b)) * b
print(f"벡터 a: {a}")
print(f"벡터 b: {b}")
print(f"a를 b에 투영: {proj}")


[과제 1 해답] 벡터 투영
벡터 a: [3 4]
벡터 b: [1 0]
a를 b에 투영: [3. 0.]


In [12]:
# [과제 2] 2x2 회전 행렬 구현
#         - 각도 θ만큼 회전하는 행렬 생성
#         - 점 (1, 0)을 45도 회전

print("\n[과제 2 해답] 회전 행렬")
def rotation_matrix(theta_degrees):
    """2D 회전 행렬 생성"""
    theta = np.radians(theta_degrees)
    return np.array([[np.cos(theta), -np.sin(theta)],
                     [np.sin(theta), np.cos(theta)]])

# 45도 회전
R = rotation_matrix(45)
point = np.array([1, 0])
rotated = R @ point

print(f"회전 행렬 (45°):\n{R}")
print(f"원본 점: {point}")
print(f"회전된 점: {rotated}")


[과제 2 해답] 회전 행렬
회전 행렬 (45°):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
원본 점: [1 0]
회전된 점: [0.70710678 0.70710678]


In [13]:

# [과제 3] 최소제곱법으로 선형 회귀
#         - 데이터: x = [1, 2, 3, 4, 5], y = [2.1, 3.9, 6.2, 7.8, 10.1]
#         - y = ax + b 형태의 직선 적합

print("\n[과제 3 해답] 최소제곱 선형 회귀")
x = np.array([1, 2, 3, 4, 5])
y = np.array([2.1, 3.9, 6.2, 7.8, 10.1])

# 설계 행렬: [x, 1]
A = np.column_stack([x, np.ones(len(x))])
print(f"설계 행렬 A:\n{A}")

# 최소제곱 해: (A.T @ A)^-1 @ A.T @ y
# 또는 np.linalg.lstsq 사용
coeffs, residuals, rank, s = np.linalg.lstsq(A, y, rcond=None)
a, b = coeffs

print(f"\ny = {a:.4f}x + {b:.4f}")

# 예측
y_pred = a * x + b
print(f"\n실제 y: {y}")
print(f"예측 y: {y_pred}")

print("\n" + "=" * 60)
print("실습 4 완료!")
print("=" * 60)



[과제 3 해답] 최소제곱 선형 회귀
설계 행렬 A:
[[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]
 [5. 1.]]

y = 1.9900x + 0.0500

실제 y: [ 2.1  3.9  6.2  7.8 10.1]
예측 y: [ 2.04  4.03  6.02  8.01 10.  ]

실습 4 완료!
